services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD}
      POSTGRES_DB: ${APP_DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - 8000:8000
    environment:
      APP_DATABASE_DSN: postgresql://${APP_DATABASE_USER}:${APP_DATABASE_PASSWORD}@db:5432/${APP_DATABASE_NAME}

volumes:
  pgdata:
