services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD}
      POSTGRES_DB: ${APP_DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_DATABASE_USER} -d ${APP_DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    command: ["-path", "/migrations", "-database", "postgres://${APP_DATABASE_USER}:${APP_DATABASE_PASSWORD}@db:5432/${APP_DATABASE_NAME}?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db

  app:
    build: .
    ports:
      - 8000:8000
    environment:
      APP_DATABASE_DSN: postgres://${APP_DATABASE_USER}:${APP_DATABASE_PASSWORD}@db:5432/${APP_DATABASE_NAME}

volumes:
  pgdata:
